## Task

1. Write a NumPy program to test element-wise for NaN of a given array.
2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
7. In the code cell below, write the code to get and display the 55th row in the dataframe df.
8. In the code cell below write the code to display the first 10 rows of the dataframe <code>df</code>.
9. In the code cell below, select and display the first eight rows from the <code>'Country'</code> and <code>'TB deaths'</code> columns.
10. In the code cell below write code to find all the rows in <code>df</code> where TB deaths exceed 10000.
11. In the code cell below find  all the countries where the Population (1000s) is **less than or equal to** 50000 **or** TB deaths are **greater than or equal to** 20000.

In [9]:
import sys
import pathlib

_p = pathlib.Path.cwd()

while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent

sys.path.insert(0, str(_p))

from db.dataraflow_db import run_query

In [1]:
# 1. 
import numpy as np

arr = np.array([1, np.nan, 3, np.nan, 5])

print(np.isnan(arr))

[False  True False  True False]

In [ ]:
# 2.
import numpy as np

arr = np.array([1, 2.5, 3+2j, 7j])

print(np.iscomplex(arr))  # Check for complex numbers
print(np.isreal(arr))    # Check for real numbers
print(np.isscalar(5))    # Is 5 a scalar?
print(np.isscalar(arr))  # Is the whole array a scalar?

[False False  True  True]
[ True  True False False]
True
False

In [3]:
# 3.
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.001, 2.5, 3.001])

result = np.isclose(a, b, atol=0.01)

print(result)

[ True False  True]

In [4]:
#4
import numpy as np

a = np.array([1, 5, 8])
b = np.array([2, 5, 6])

print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))

[False False  True]
[False  True  True]
[ True False False]
[ True  True False]

In [5]:
# 5.
import numpy as np

a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.001, 4.0])

# Exact element-wise equality
print(np.equal(a, b))

# Equality within a tolerance
print(np.isclose(a, b, atol=0.01))

[ True False False]
[ True  True False]

In [6]:
# 6
import numpy as np

arr = np.array([1, 7, 13, 105])

print(arr.nbytes)

32

In [12]:
# 7
data = run_query("SELECT * FROM week06.who_pop_tb_some")

In [ ]:
data.shape

# data.iloc[54] wont work as this datafram only have 12 rows

(12, 3)

In [ ]:
# 8
data.head(10)

                 Country  Population (1000s)  TB deaths
0                 Angola               21472       6900
1                 Brazil              200362       4400
2                  China             1393337      41000
3      Equatorial Guinea                 757         67
4          Guinea-Bissau                1704       1200
5                  India             1252140     240000
6             Mozambique               25834      18000
7               Portugal               10608        140
8     Russian Federation              142834      17000
9  Sao Tome and Principe                 193         18

In [20]:
# 9
data[['Country', 'TB deaths']].head(8)

             Country  TB deaths
0             Angola       6900
1             Brazil       4400
2              China      41000
3  Equatorial Guinea         67
4      Guinea-Bissau       1200
5              India     240000
6         Mozambique      18000
7           Portugal        140

In [21]:
# 10

data[data['TB deaths'] > 10000]

               Country  Population (1000s)  TB deaths
2                China             1393337      41000
5                India             1252140     240000
6           Mozambique               25834      18000
8   Russian Federation              142834      17000
10        South Africa               52776      25000

In [22]:
# 11
data[(data['Population (1000s)'] <= 50000) | (data['TB deaths'] >= 20000)]

                  Country  Population (1000s)  TB deaths
0                  Angola               21472       6900
2                   China             1393337      41000
3       Equatorial Guinea                 757         67
4           Guinea-Bissau                1704       1200
5                   India             1252140     240000
6              Mozambique               25834      18000
7                Portugal               10608        140
9   Sao Tome and Principe                 193         18
10           South Africa               52776      25000
11            Timor-Leste                1133        990

## Assignment

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.


2. Write a Python program to convert a Panda module Series to Python list and it's type.


3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


4. Write a Python program to get the largest integer smaller or equal to the division of the inputs.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


5. Write a Python program to convert a dictionary to a Pandas series.
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64


6. Write a Python program to convert a NumPy array to a Pandas series.
Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64


7. Write a Python program to change the data type of given a column or a Series.
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64


8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']



 
10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object


11. Write a Pandas program to sort a given Series.
Sample Output:
Original Data Series: 0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object


12. Write a Pandas program to add some data to an existing Series.
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object

In [24]:
# Assignment

import pandas as pd

data = [10, 20, 30, 40, 50]

Panda_series = pd.Series(data)

print(Panda_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [26]:
# 2. 

series = pd.Series([10, 20, 30, 40, 50])

my_list = series.tolist()

print(my_list)
print(type(my_list))

[10, 20, 30, 40, 50]
<class 'list'>

In [28]:
# 3.

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print(s1+s2)  # Addition
print(s1-s2)  # Subtraction
print(s1*s2)  # Multiplication
print(s1/s2)  # Division

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
# 4

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

result = s1//s2

print(result)

0    2
1    1
2    1
3    1
4    1
dtype: int64

In [30]:
# 5

data = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

series = pd.Series(data)

print(series)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [31]:
# 6

arr = np.array([10, 20, 30, 40, 50])

series = pd.Series(arr)

print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# 7
s = pd.Series([100, 200, 'python', 300.12, 400])

result = pd.to_numeric(s, errors='coerce')

print(result)

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [34]:
# 8

df = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})

first_col = df['col1']

print("1st column as a Series:")
print(first_col)
print(type(first_col))

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.Series'>

In [35]:
# 9

s = pd.Series([100, 200, 'python', 300.12, 400])

arr = s.to_numpy()

print(arr)

[100 200 'python' 300.12 400]

In [36]:
# 10
import pandas as pd

s = pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']
])

result = s.explode()

print(result)

0       Red
0     Green
0     White
1       Red
1     Black
2    Yellow
dtype: str

In [38]:
# 11

import pandas as pd

s = pd.Series([100, 200, 'python', 300.12, 400])

print("Original Data Series:")
print(s)

print(s.astype(str).sort_values())

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: str

In [39]:
# 12

import pandas as pd

s = pd.Series([100, 200, 'python', 300.12, 400])
new_data = pd.Series([500, 'php'])

result = pd.concat([s, new_data])

print("Data Series after adding some data:")
print(result)

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

## Assessment

#### The datasets now live in the cohort database (schema `week06`)

The six airport weather datasets are the tables:

```
week06.beijing_pek_2014, week06.brasilia_bsb_2014, week06.capetown_cpt_2014,
week06.delhi_del_2014,   week06.london_2014,       week06.moscow_svo_2014
```

Pull them with SQL and explore them — see **`Data Access (SQL).md`** in this week's folder
for the connection snippet and worked examples. For example:

```python
from db.dataraflow_db import run_query
london = run_query("SELECT * FROM week06.london_2014")
```

Run your analysis on them, and detail your findings below as much as you can.

---
## SQL Assessment (Intermediate SQL)

This part tests what you learnt in **`4-Intermediate SQL/Intermediate SQL.ipynb`**. Every task runs against the
**live cohort database** using your **read-only** account.

**How it works**
1. Run the **SQL setup** cell below first (and again after restarting the kernel).
2. In each task cell, write your query **between the triple quotes**, then run the cell.
3. `answer(...)` runs your query, shows the result, and tells you if it's ✅ correct. If not, it tells you
   whether the **shape** (rows × columns) is right, so you know where to look.
4. Match the **column order**, **sort order** and **rounding** asked for. Column *names* aren't checked,
   but use the names given.
5. Run `sql_score()` at the end to see your SQL score.

Writes are blocked: the database is read-only, so build everything inside your `SELECT` (CTEs are your workspace).

### SQL Task 1 · Exploring the schema
Using `INFORMATION_SCHEMA.COLUMNS`, list every table in the **`week06`** schema with **how many columns** it has.

**Return:** `table_name`, `n_columns`, sorted by `table_name` (A→Z).
*Revisit: Intermediate SQL §1.*

In [ ]:
SQL_01 = """

"""
answer("s01", SQL_01)

:

In [47]:
SQL_01 = """
SELECT
    TABLE_NAME AS table_name,
    COUNT(*) AS n_columns
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'week06'
GROUP BY TABLE_NAME
ORDER BY table_name;
"""

answer("s01", SQL_01)

          table_name  n_columns
0   beijing_pek_2014         23
1  brasilia_bsb_2014         23
2  capetown_cpt_2014         23
3     delhi_del_2014         23
4        london_2014         23
5    moscow_svo_2014         23
6     who_pop_tb_all          3
7    who_pop_tb_some          3

✅ s01: correct!

### SQL Task 2 · Filtering & NULLs
For **London** (`week06.london_2014`), return **one row** with three counts:
1. `no_event_days`: days with **no event recorded**
2. `rain_days`: days whose event mentions **Rain** anywhere (e.g. `Rain`, `Fog-Rain`, `Rain-Thunderstorm`)
3. `wet_but_no_event_days`: days with **no event recorded** but `Precipitationmm > 0`

⚠️ The events column name starts with a **space**: `[ Events]`. And remember, `= NULL` never matches.
*Revisit: §1.2, §3.2, §3.3.*

In [49]:
SQL_02 = """
SELECT
    SUM(CASE
        WHEN [ Events] IS NULL THEN 1
        ELSE 0
    END) AS no_event_days,

    SUM(CASE
        WHEN [ Events] LIKE '%Rain%' THEN 1
        ELSE 0
    END) AS rain_days,

    SUM(CASE
        WHEN [ Events] IS NULL AND Precipitationmm > 0 THEN 1
        ELSE 0
    END) AS wet_but_no_event_days

FROM week06.london_2014;
"""

answer("s02", SQL_02)

   no_event_days  rain_days  wet_but_no_event_days
0            114        238                      6

✅ s02: correct!

### SQL Task 3 · CASE & conditional aggregation
From `week16.customer_churn_prediction`, for each `Contract_Type` return: number of `customers`, number
`churned` (`Churn = 1`), and `churn_rate_pct` (percentage, **rounded to 1 decimal place**).

**Return:** `Contract_Type`, `customers`, `churned`, `churn_rate_pct`, sorted by `churn_rate_pct` (highest first).
⚠️ Watch out for the integer-division trap. *Revisit: §4.4, §5.2.*

In [50]:
SQL_03 = """
SELECT
    Contract_Type,
    COUNT(*) AS customers,
    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned,
    ROUND(
        100.0 * SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END)
        / COUNT(*),
        1
    ) AS churn_rate_pct
FROM week16.customer_churn_prediction
GROUP BY Contract_Type
ORDER BY churn_rate_pct DESC;
"""

answer("s03", SQL_03)

    Contract_Type  customers  churned  churn_rate_pct
0  Month-to-Month        158       91            57.6
1        One Year        165       89            53.9
2        Two Year        177       48            27.1

✅ s03: correct!

### SQL Task 4 · GROUP BY + HAVING
From `week09.comtrade_milk_uk_monthly_14`, find the partner countries the UK **exported** milk to in
**all 12 months** of 2014, with the **total export value**.

**Return:** `Partner`, `total_exports_usd`, sorted by `total_exports_usd` (highest first).
⚠️ Exclude the `'World'` total row. *Revisit: §6.2.*

In [56]:
SQL_04 = """
SELECT
    Partner,
    SUM([Trade Value (US$)]) AS total_exports_usd
FROM week09.comtrade_milk_uk_monthly_14
WHERE [Trade Flow] = 'Exports'
  AND [Year] = 2014
  AND Partner <> 'World'
GROUP BY Partner
HAVING COUNT(DISTINCT [Period]) = 12
ORDER BY total_exports_usd DESC;
"""

answer("s04", SQL_04)

                 Partner  total_exports_usd
0                Ireland          421228441
1                Algeria           93753841
2            Netherlands           68649082
3                Germany           36096633
4                 France           34622982
5                Belgium           29343007
6                  China           27317861
7   China, Hong Kong SAR           19847947
8                Nigeria           12932371
9                 Guinea           12018176
10               Lebanon           10400613
11                 Congo            6407358
12                 Spain            3548528
13  United Arab Emirates            3264368
14               Denmark            2908457

✅ s04: correct!

### SQL Task 5 · JOIN across two sources
Join WHO TB data (`week06.who_pop_tb_all`) with World Bank population (`week08.wb_pop_2013`) on the country
name. Compute **TB deaths per 100,000 people** using the **World Bank** population (`[SP.POP.TOTL]`),
**rounded to 1 decimal place**.

**Return:** the **top 5** countries: `Country`, `tb_deaths_per_100k`, highest first.
*Revisit: §7.2–7.3.*

In [59]:
SQL_05 = """
SELECT TOP 5
    tb.Country,
    ROUND(
        100000.0 * tb.[TB deaths] / wb.[SP.POP.TOTL],
        1
    ) AS tb_deaths_per_100k
FROM week06.who_pop_tb_all AS tb
INNER JOIN week08.wb_pop_2013 AS wb
    ON tb.Country = wb.country
WHERE wb.[SP.POP.TOTL] > 0
ORDER BY tb_deaths_per_100k DESC;
"""

answer("s05", SQL_05)

       Country  tb_deaths_per_100k
0     Djibouti               100.6
1      Nigeria                92.6
2    Swaziland                88.0
3  Timor-Leste                83.9
4      Somalia                75.0

✅ s05: correct!

### SQL Task 6 · Anti-join
How many WHO countries in `week06.who_pop_tb_all` have **no matching country name** in `week08.wb_pop_2013`?

**Return:** one row, one column (`who_countries_without_wb_match`).
*Revisit: §7.4. Bonus thought: why do these countries fail to match?*

In [61]:
SQL_06 = """
SELECT
    COUNT(*) AS who_countries_without_wb_match
FROM week06.who_pop_tb_all AS who
WHERE NOT EXISTS (
    SELECT 1
    FROM week08.wb_pop_2013 AS wb
    WHERE wb.country = who.Country
);
"""

answer("s06", SQL_06)

   who_countries_without_wb_match
0                              28

✅ s06: correct!

### SQL Task 7 · UNION ALL
Stack the **six** city weather tables in `week06` and compute each city's **average `Mean TemperatureC`**
for 2014, **rounded to 1 decimal place**. Use exactly these city labels:
`'Beijing'`, `'Brasilia'`, `'Cape Town'`, `'Delhi'`, `'London'`, `'Moscow'`.

**Return:** `city`, `avg_mean_temp_c`, sorted by `city` (A→Z).
⚠️ `Mean TemperatureC` is stored as a whole number, so watch the integer-division trap. *Revisit: §8.1–8.2.*

In [65]:
SQL_07 = """
SELECT
    city,
    ROUND(AVG(1.0 * [Mean TemperatureC]), 1) AS avg_mean_temp_c
FROM (
    SELECT 'Beijing' AS city, [Mean TemperatureC]
    FROM week06.beijing_pek_2014

    UNION ALL

    SELECT 'Brasilia' AS city, [Mean TemperatureC]
    FROM week06.brasilia_bsb_2014

    UNION ALL

    SELECT 'Cape Town' AS city, [Mean TemperatureC]
    FROM week06.capetown_cpt_2014

    UNION ALL

    SELECT 'Delhi' AS city, [Mean TemperatureC]
    FROM week06.delhi_del_2014

    UNION ALL

    SELECT 'London' AS city, [Mean TemperatureC]
    FROM week06.london_2014

    UNION ALL

    SELECT 'Moscow' AS city, [Mean TemperatureC]
    FROM week06.moscow_svo_2014
) AS all_cities
GROUP BY city
ORDER BY city;
"""

answer("s07", SQL_07)

        city  avg_mean_temp_c
0    Beijing             13.4
1   Brasilia             22.9
2  Cape Town             17.6
3      Delhi             13.7
4     London             12.3
5     Moscow              6.0

✅ s07: correct!

### SQL Task 8 · CTE + window ranking (top-1 per group)
For **London**, find the **hottest day of each month** (highest `Max TemperatureC`). If two days tie,
take the **earlier** date.

**Return:** `month_no`, `day` (a real **date**, convert `GMT` with `TRY_CONVERT(date, GMT)`), `max_temp`,
sorted by `month_no`. *Revisit: §10, §11.3.*

In [66]:
SQL_08 = """
WITH daily_temps AS (
    SELECT
        MONTH(TRY_CONVERT(date, GMT)) AS month_no,
        TRY_CONVERT(date, GMT) AS [day],
        [Max TemperatureC] AS max_temp
    FROM week06.london_2014
    WHERE TRY_CONVERT(date, GMT) IS NOT NULL
),
ranked_days AS (
    SELECT
        month_no,
        [day],
        max_temp,
        ROW_NUMBER() OVER (
            PARTITION BY month_no
            ORDER BY max_temp DESC, [day] ASC
        ) AS rn
    FROM daily_temps
)
SELECT
    month_no,
    [day],
    max_temp
FROM ranked_days
WHERE rn = 1
ORDER BY month_no;
"""

answer("s08", SQL_08)

    month_no         day  max_temp
0          1  2014-01-05        12
1          2  2014-02-24        14
2          3  2014-03-09        19
3          4  2014-04-01        19
4          5  2014-05-19        26
5          6  2014-06-09        26
6          7  2014-07-18        30
7          8  2014-08-06        26
8          9  2014-09-18        26
9         10  2014-10-31        23
10        11  2014-11-01        18
11        12  2014-12-17        13

✅ s08: correct!

### SQL Task 9 · Running total
From `week09.comtrade_milk_uk_monthly_14`, compute the UK's **total milk exports per month** (exclude `'World'`)
and a **year-to-date running total**.

**Return:** `Period`, `exports_usd`, `ytd_exports_usd`, sorted by `Period`. *Revisit: §11.4–11.5.*

In [67]:
SQL_09 = """
WITH monthly_exports AS (
    SELECT
        [Period],
        SUM([Trade Value (US$)]) AS exports_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE [Trade Flow] = 'Exports'
      AND Partner <> 'World'
      AND [Year] = 2014
    GROUP BY [Period]
)
SELECT
    [Period],
    exports_usd,
    SUM(exports_usd) OVER (
        ORDER BY [Period]
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS ytd_exports_usd
FROM monthly_exports
ORDER BY [Period];
"""

answer("s09", SQL_09)

    Period  exports_usd  ytd_exports_usd
0   201401     87138654         87138654
1   201402     72489716        159628370
2   201403     86781424        246409794
3   201404     95195778        341605572
4   201405     96201135        437806707
5   201406     99315900        537122607
6   201407     72878716        610001323
7   201408     61737703        671739026
8   201409     60600293        732339319
9   201410     57003417        789342736
10  201411     49293958        838636694
11  201412     60015241        898651935

✅ s09: correct!

### SQL Task 10 · Business question
The Head of Credit asks: *"How does the approval rate vary by property area and credit history?"*
Using `week17.loan_approval_prediction`, return one row per `Property_Area` × `Credit_History` combination
that exists in the data, with the number of `applications` and the `approval_rate_pct` (rounded to 1 decimal).

**Return:** `Property_Area`, `Credit_History`, `applications`, `approval_rate_pct`, sorted by `Property_Area`
then `Credit_History`. Then answer reflection question 3 below about what you see.

In [ ]:
# Lets check what the column loan approved contain
q("""
SELECT Loan_Approved, COUNT(*) AS applications
FROM week17.loan_approval_prediction
GROUP BY Loan_Approved
ORDER BY Loan_Approved;
""")

   Loan_Approved  applications
0              0           166
1              1           334

In [72]:
# now that we know what it entails

SQL_10 = """
SELECT
    Property_Area,
    Credit_History,
    COUNT(*) AS applications,
    ROUND(
        100.0 * SUM(
            CASE WHEN Loan_Approved = 1 THEN 1 ELSE 0 END
        ) / COUNT(*),
        1
    ) AS approval_rate_pct
FROM week17.loan_approval_prediction
GROUP BY
    Property_Area,
    Credit_History
ORDER BY
    Property_Area,
    Credit_History;
"""
answer("s10", SQL_10)

  Property_Area  Credit_History  applications  approval_rate_pct
0         Rural               0           166                0.0
1     Semiurban               1           167              100.0
2         Urban               1           167              100.0

✅ s10: correct!

### SQL reflection
Answer in the cell below (2–3 sentences each):

1. In Task 3 or Task 7, what would `AVG(Churn)` or `AVG([Mean TemperatureC])` return **without** converting to a
   decimal first, and why?
2. In Task 6, why do those countries fail to match? How would you fix this in a real project?
3. Look at your Task 10 result. What is **suspicious** about it? What would you tell the Head of Credit before
   anyone trains a model on this data?

**My answers:**

1. If we calculate an average without converting the numbers to decimals, SQL may give us a whole number and leave out the decimal part, depending on the data types and how the calculation is performed. For example, the average of 2, 3, and 4 is 3, but the average of 2, 3, and 5 is 3.33. Converting the numbers to decimals first helps SQL keep the decimal part so we get a more accurate result.
2. Since we tried matching it through the country name WHO.country = World.country, some of the countries might not match even if they represent the same country due to extra spaces or if one is abbrevated and the other one is writteen in full. If i want to fix this, i will standardize the country name or use a unique code that identifies the country instaed of relying only on names
3. Becuase we cant tell for sure if the credit_history or other variables that is effectively affecting the approval outcome, this needs to be determined before building a model.

### SQL score
Run this when you're done.

In [73]:
sql_score()

Task                          Topic Result
 s01           Exploring the schema      ✅
 s02              Filtering & NULLs      ✅
 s03 CASE & conditional aggregation      ✅
 s04              GROUP BY + HAVING      ✅
 s05            JOIN across sources      ✅
 s06                      Anti-join      ✅
 s07                      UNION ALL      ✅
 s08           CTE + window ranking      ✅
 s09         Running total (window)      ✅
 s10              Business question      ✅

SQL score: 10 / 10

### This article contains what i learnt, the problems I solved, the challenges i faced and how I overcame them

Article Link: https://medium.com/@mustaphasodiq95/dataraflow-week-6-sql-had-other-plans-for-me-00555198fd09